backend:
  name: github
  repo: invmy/astro-theme-cactus
  branch: main # Branch to update (optional; defaults to master)
  site_domain: https://754321.xyz
  base_url: https://754321.xyz
  auth_endpoint: /api/auth

media_folder: src/assets/images
public_folder: /assets/images

collections:
  # Post collection
  - name: 'post'
    label: 'POST'
    folder: 'src/content/post'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '标题', name: 'title', widget: 'string' ,required: true}
      - { label: '发布日期', name: 'publishDate', widget: 'datetime', date_format: "YYYY-MM-DD", required: true}
      - { label: '描述', name: 'description', widget: 'string' ,required: true}
      - { label: "标签", name: "tags", widget: "list" }
      - { label: '正文', name: 'body', widget: 'markdown' }

  # Note collection
  - name: 'note'
    label: 'NOTE'
    folder: 'src/content/note'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '标题', name: 'title', widget: 'string' ,required: true}
      - { label: '发布日期', name: 'publishDate', widget: 'datetime' ,required: true}
      - { label: '正文', name: 'body', preview: true, widget: 'markdown' }